apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::853294253875:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HVFY86NBPMIX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-04T15:48:25Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-04T15:48:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1688"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a5e1dc78-df4f-443b-b752-ce17c61a5152
